In [1]:
###     Assignment - Indexing and Slicing
#1. Write a NumPy program to generate six random integers between 10 and 30.
import numpy as np
import random as random
quest1 = np.random.randint(10,30,size = 6)
print(quest1)




[20 18 14 22 22 12]


In [2]:
#   2. Write a NumPy program to create a 3x3 matrix with values ranging from 20 to 28.

import numpy as np
ques2 = np.arange(20,29).reshape(3,3)
print(ques2)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [12]:
#   3. Write a NumPy program to create a vector filled with 1s of size 10 and update the sixth value to 25.
quest3 = np.ones(10, dtype = int)
print(quest3)

print("sixth value:",quest3[5],"updating it to",quest3[5]*25)
quest3[5] = 25
print(quest3)


[1 1 1 1 1 1 1 1 1 1]
sixth value: 1 updating it to 25
[ 1  1  1  1  1 25  1  1  1  1]


In [4]:
#   4. Write a program to get fourth and seventh elements from the following array and add them.
quest4 = np.arange(10,30)
print(quest4)
print("Fourth and sevent element are:",quest4[3],quest4[6],"and their sum is:",quest4[3] + quest4[6])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Fourth and sevent element are: 13 16 and their sum is: 29


In [5]:
#   5. Write a program to get the first three elements of the second column of the array.

quest5 = np.arange(20,35).reshape(5,3)
print(quest5,"\n")
print(quest5[:3:1,1:2:1])



[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]] 

[[21]
 [24]
 [27]]
